version: '3'

networks:
  gpicm-development:
    name: 'gpicm-development'

services:

  app:
    container_name: gpcim-nestjs-app
    restart: always
    command: sh -c "npm run db:deploy && yarn start:dev"
    build:
      context: .
      target: development
    env_file:
      - .env
    environment:
      DATABASE_URL: mysql://local:12345678@db:3306/anselmo_telemetria
    volumes:
      - .:/usr/src/app:cached
      - /usr/src/app/node_modules
      - ./public/assets:/usr/src/app/public/assets
    ports:
      - '9000:9000'
    networks:
      - gpicm-development
    user: "1000:1000"
    depends_on:
      - db

  db:
    container_name: db
    image: 'mariadb:10.5'
    environment:
      MARIADB_USER: local
      MARIADB_PASSWORD: 12345678
      MARIADB_ROOT_PASSWORD: mariadbrootPW
      MARIADB_DATABASE: anselmo_telemetria
    volumes:
      - 'mariadb-data:/var/lib/mysql'
    ports:
      - 3306:3306
    networks:
      - gpicm-development

  redis:
    image: redis
    container_name: weather-redis
    command: ["redis-server", "--appendonly", "no", "--save", "", "--dir", "/data"]
    restart: always
    ports:
      - 6333:6379
    networks:
      - gpicm-development

volumes:
  mariadb-data:
    name: gpicm-dev-db