version: '3'

networks:
  gpicm-production:
    name: 'gpicm-production'

services:

  web: 
    container_name: "gpcim-react-app"
    image: fonsecabarreto/weather-react-app:latest
    mem_limit: 128m
    hostname: web
    ports:
      - 3000:8080
    networks:
      - gpicm-production

  redis:
    image: redis
    container_name: gpcim-weather-redis
    command: ["redis-server", "--appendonly", "no", "--save", "", "--dir", "/data"]
    restart: always
    ports:
      - 6333:6379
    networks:
      - gpicm-production

  api:
    image: fonsecabarreto/gpicm-nestjs-app:latest
    container_name: gpcim-nestjs-api
    env_file:
      - .env.production
    ports:
      - '9000:9000'
    networks:
      - gpicm-production
      
  worker1:
    image: fonsecabarreto/gpicm-metrics-computation:latest
    container_name: gpcim-metrics-computation
    env_file:
      - .env.production
    ports:
      - '3001:3001'
    networks:
      - gpicm-production

  worker2:
    image: fonsecabarreto/gpicm-sync-engine:latest
    container_name: gpicm-sync-engine
    env_file:
      - .env.production
    ports:
      - '3002:3001'
    networks:
      - gpicm-production