version: '3'

networks:
  gpicm-development:
    name: 'gpicm-development'

services:

  app:
    container_name: gpcim-nestjs-app
    restart: always
    command: sh -c "yarn run prisma:generate && yarn run start:dev"
    build:
      context: .
      target: development
    env_file:
      - .env.local
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - '9000:9000'
    networks:
      - gpicm-development

  db:
    container_name: db
    image: 'mariadb:10.5'
    environment:   
      MARIADB_USER: lucas
      MARIADB_PASSWORD: 12345678
      MARIADB_ROOT_PASSWORD: mariadbrootPW
      MARIADB_DATABASE: anselmo_telemetria_react
    volumes:
      - 'mariadb-data:/var/lib/mysql'
    ports:
      - 3306:3306
    networks:
      - gpicm-development

  read-db:
    container_name: read-db
    image: 'mariadb:10.5'
    environment:   
      MARIADB_USER: lucas
      MARIADB_PASSWORD: 12345678
      MARIADB_ROOT_PASSWORD: mariadbrootPW
      MARIADB_DATABASE: anselmo_telemetria_readonly
    volumes:
      - 'mariadb-data-readonly:/var/lib/mysql'
    ports:
      - 3307:3306
    networks:
      - gpicm-development

  redis:
    image: redis
    container_name: weather-redis
    command: ["redis-server", "--appendonly", "no", "--save", "", "--dir", "/data"]
    restart: always
    ports:
      - 6333:6379
    networks:
      - gpicm-development

volumes:
  mariadb-data:
    name: gpicm-dev-db
  mariadb-data-readonly:
    name: gpicm-readonly-dev-db
  node_modules:
    name: "gpicm-node-modules"