INSERT INTO anselmo_telemetria.incident_types
(id, name, description, internal_id, image_url, slug)
VALUES
(8, 'AMEAÇA DE QUEDA DE CAIXA D''ÁGUA', '', 70, NULL, 'ameaa-de-queda-de-caixa-dgua'),
(21, 'ACIDENTE COM PP', '', 83, NULL, 'acidente-com-pp'),
(22, 'ALAGAMENTO', '', 84, NULL, 'alagamento'),
(23, 'CHUVA DE GRANIZO', '', 85, NULL, 'chuva-de-granizo'),
(24, 'ENXURRADA', '', 86, NULL, 'enxurrada'),
(25, 'INFILTRAÇÃO', '', 87, NULL, 'infiltrao'),
(26, 'INUNDAÇÃO', '', 88, NULL, 'inundao'),
(31, 'Outro', '', 5, NULL, 'outro'),
(32, 'AMEAÇA DE DESABAMENTO DE IMÓVEL', '', 64, NULL, 'ameaa-de-desabamento-de-imvel'),
(33, 'AMEAÇA DE DESABAMENTO DE MARQUISE', '', 65, NULL, 'ameaa-de-desabamento-de-marquise'),
(34, 'AMEAÇA DE DESABAMENTO DE MURO', '', 66, NULL, 'ameaa-de-desabamento-de-muro'),
(35, 'AMEAÇA DE DESLIZAMENTO DE BARREIRA', '', 67, NULL, 'ameaa-de-deslizamento-de-barreira'),
(36, 'AMEAÇA DE DESPRENDIMENTO DE REBOCO', '', 68, NULL, 'ameaa-de-desprendimento-de-reboco'),
(37, 'AMEAÇA DE QUEDA DE ÁRVORE', '', 69, NULL, 'ameaa-de-queda-de-rvore'),
(38, 'AMEAÇA DE ROLAMENTO DE PEDRA', '', 71, NULL, 'ameaa-de-rolamento-de-pedra'),
(39, 'IMOVEL/ESTRUTURA COM TRINCAS E/OU RACHADURAS', '', 72, NULL, 'imovelestrutura-com-trincas-eou-rachaduras'),
(40, 'DESABAMENTO DE IMÓVEL', '', 73, NULL, 'desabamento-de-imvel'),
(41, 'DESABAMENTO DE MARQUISE', '', 74, NULL, 'desabamento-de-marquise'),
(42, 'DESABAMENTO DE MURO', '', 75, NULL, 'desabamento-de-muro'),
(43, 'DESABAMENTO DE REBOCO', '', 76, NULL, 'desabamento-de-reboco'),
(44, 'DESLIZAMENTO DE BARREIRA', '', 77, NULL, 'deslizamento-de-barreira'),
(45, 'DESLIZAMENTO DE ENCOSTA', '', 78, NULL, 'deslizamento-de-encosta'),
(46, 'INCENDIO EM VEGETAÇÃO DE ÁREAS NÃO PROTEGIDAS', '', 79, NULL, 'incendio-em-vegetao-de-reas-no-protegidas'),
(47, 'INCENDIO EM VEGETAÇÃO DE PARQUES. APA OU APP', '', 80, NULL, 'incendio-em-vegetao-de-parques-apa-ou-app'),
(48, 'INCENDIO URBANO EM AGLOMERADOS RESIDENCIAIS', '', 81, NULL, 'incendio-urbano-em-aglomerados-residenciais'),
(49, 'INCENDIO URBANO EM PLANTAS INDUSTRIAIS E DEPÓSITOS', '', 82, NULL, 'incendio-urbano-em-plantas-industriais-e-depsitos'),
(50, 'QUEDA DE ARVORE', '', 89, NULL, 'queda-de-arvore'),
(51, 'QUEDA DE CAIXA D''AGUA', '', 90, NULL, 'queda-de-caixa-dagua'),
(52, 'ROLAMENTO DE PEDRA', '', 91, NULL, 'rolamento-de-pedra'),
(53, 'VENDAVAL', '', 92, NULL, 'vendaval');
